title: Daily Trend
description: Daily Trend — short daily posts and trends
baseurl: "/dailytrendhubforyou" # the subpath of your site, e.g. /repo
url: "https://dailytrendhub.github.io" # <- replace USERNAME with your GitHub username
theme: minima
plugins: [jekyll-feed]
markdown: kramdown
paginate: 5
sass:
  sass_dir: assets/css
