title: "Daily Trend Hub"
email: your-email@example.com
description: "Your go-to site for daily trending news, updates, and insights."
baseurl: "/dailytrendhubforyou" # The name of your repo if hosting on GitHub Pages
url: "https://DailyTrendHub.github.io" # Replace with your GitHub username

# Build settings
theme: minima
markdown: kramdown
paginate: 5
paginate_path: "/page:num"

plugins:
  - jekyll-feed
  - jekyll-paginate
sass:
  sass_dir: assets/css
  style: compressed  # Minifies CSS for better performance
  sourcemap: never   # Disables sourcemaps in production

# Exclude files/folders that don't need to be built
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - vendor

collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:title/
  pages:
    output: true
    permalink: /:path/
  stories:
    output: true
    permalink: /trending-stories/:title/

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_stories" 
      type: "stories"
    values:
      layout: "story"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

# IMPORTANT: Also include this
include:
  - _pages
  - _stories
  - _includes
